config/routes.rb
Newapp::Application.routes.draw do
  resources :users, :charges, :profiles, :sessions

  root :to => "home#index"

  #mapping new routes
  match '/home/terms', :controller =>'home', :action => 'terms'
  match '/home/privacy', :controller =>'home', :action => 'privacy'
  match '/home/noc', :controller => 'home', :action => 'noc'
  match '/charges/show', :controller => 'charges', :action => 'show'
  match '/users/passcreate', :controller => 'users', :action => 'passcreate'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :password, :email, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :email, :on => :create
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :condition, :email, :name, :curation
  #has_secure_password, :on => :passcreate

  validates_presence_of :password, :on => :passcreate

  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :condition, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_profile
    @current_profile ||= Profile.find(session[:profile_id]) if session[:profile_id]
  end

  helper_method :current_profile
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new

end

def create
	# Amount in cents
  	@amount = params[:amount2]

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	 # Stripe::Charge.create(
	 #   :customer    => customer.id,
	  #  :amount      => @amount,
	   # :description => 'Rails Stripe customer',
	   # :currency    => 'usd'
	 # )

	if @amount == '1500'
		curation = "2 Days";
	elsif @amount == '900'
		curation = "5 Days";
	else
		curation = "10 Days";
	end

	 User.find(params[:id]).update_attributes(:name => customer.id, :curation => curation)

	UserSignup.notification.deliver
	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  render "create"
end
  def show
    	@user = User.find(params[:id])
    	@days = params[:days]

    	if @days == "2 Days - $15.00"
    		n_day = "2 Days";
    	elsif @days == "5 Days - $9.00"
    		n_day = "5 Days";
    	else
    		n_day = "10 Days";
    	end
    	NoPay.nopayNotification.deliver
    	User.find(params[:id]).update_attributes(:curation => n_day)
    	respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def terms
  end
  def privacy
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "Wellbeadmin@12", :only => :index
  def new
      @profile = Profile.new
    end

  def index
    @profile = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @profile = Profile.new(params[:profile])
    if @profile.save
      session[:profile_id] = @profile.id
      redirect_to :controller => "sessions", :action => "show", :id => session[:profile_id], :notice => "Profile Created!"
    else
      render "new"
    end
  end

    def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    profile = Profile.find_by_email(params[:email])
    if profile && profile.authenticate(params[:password])
      session[:profile_id] = profile.id
      redirect_to :action => "show", :id => session[:profile_id] , :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def show
    @profile = Profile.find(current_profile)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def destroy
    session[:profile_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
      http_basic_authenticate_with :name => "admin", :password => "Wellbeadmin@12", :only => :index
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

def passcreate
  @user = User.find(params[:email])
      respond_to do |format|
      format.html # pascreate.html.erb
      format.json { render json: @users }
  end
end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(request.protocol, request.host_with_port, @user).deliver
        #UserMailer.welcome_email(@user).deliver
        
        format.html { redirect_to @user, notice: 'User added successfully' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/_charge15.html.erb
<%= form_tag charges_path do %>
<div class="row" style="margin: 40px 0px 0px 30px;">
<div class="span2" style="margin: 0px 0px 0px 50px;">
	<select style="width: 140px;">
  		<option value='1500' name="amount2"> 2 Days - $15.00 </option>
  		<option value="900" name="amount2"> 5 Days - $9.00 </option>
  		<option value="500" name="amount2"> 10 Days - $5.00 </option>
	</select>
</div>
<div class="span3" style="width:121px;">
 <button id="customButton" onclick=StripeCheckout.open()>Purchase</button>
  </div>
</div>
 <script>
    $('#customButton').click(function(){
      var token = function(res){
        console.log('Got token ID:', res.id);
      };

      StripeCheckout.open({
        key:         'pk_test_BGjeOsizNGYO1XX48cU69ecg',
        panelLabel:  'Checkout',
        token:       token
      });

      return false;
    });
  </script>
<input type="hidden" value="<%= params[:id] %>" name="id"></input>
<% end %>

app/views/charges/_charge5.html.erb
<%= form_tag charges_path do %>
<div style="margin: 30px 0px 30px 0px;">
  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="pk_live_3qVrKvlqKA0DbFFwEtBCQrJG"
          data-description="You'll get your info in 10 days!"
          data-amount="500"></script>
     <input type="hidden" value = "500" name="amount"/>
     <input type="hidden" value = "10 Days" name = "curation"/>
   </div>
<% end %>

app/views/charges/_charge9.html.erb
<%= form_tag charges_path do %>
<div style="margin: 30px 0px 30px 0px;">
  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="pk_live_3qVrKvlqKA0DbFFwEtBCQrJG"
          data-description="You'll get your info in 5 days!"
          data-amount="900"
          ></script>
          <input type="hidden" value = "900" name="amount"/>
          <input type="hidden" value = "5 days" name = "curation"/>
</div>
<% end %>

app/views/charges/_chargeNoStripe.html.erb
<%= form_tag "/charges/show", :id => 'nochargeform' do %>
<div class="span2" >
  <%= select_tag "days", "<option>Select an option</option><option>10 Days - $5.00</option><option>5 Days - $9.00</option><option>2 Days - $15.00</option>".html_safe %>
</div>
<input type="hidden" value="<%= params[:id] %>" name="id"></input>
<div class="span3" style="width:121px;">
   <button action="submit" class="btn btn-info btn-large">Submit</button>
  </div>
<% end %>

app/views/charges/create.html.erb
<span style="text-align: center;">
<h2>Thanks for choosing Wellbe!</h2> 
<h3><em>You have not been charged</em></h3>
<h3>You will receive an email when your personalized content is ready to view!</h3>

<p style="text-align:center;">If you'd like to go back <%= link_to 'click here', :controller => "home", :action => "index" %>.</p>

</span>

app/views/charges/show.html.erb
<span style="text-align: center;">
<h2>Thanks for choosing Wellbe!</h2> 
<h3>As a beta user, you will not be charged for our curation service. Please bear with us as we work out the kinks and learn how to serve you the information you need as quickly as possible.</br>~Team Wellbe</h3>

<p style="text-align:center;">If you'd like to go back <%= link_to 'click here', :controller => "home", :action => "index" %>.</p>

</span>

app/views/home/index.html.erb
    <body style="background-image:url(/assets/ricepaper2.png);">
        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="well" style="padding-left:24px;">

                <div id="myCarousel" class="carousel slide" data-interval="10000">
             <!-- Carousel items -->
                    <div class="carousel-inner">
                    <div class="active item"><img src="/assets/wellbe.png" class="img-rounded" style="z-index: 0; position: relative; margin:0px auto;" /></div>
                    <div class="item"><img src="/assets/Googless.png" class="img-rounded" style="margin: 0px auto; height:285px;"/> </div>
                     <div class="item"><img src="/assets/WellbeSS.png" class="img-rounded" style="margin: 0px auto; height:285px;"/> </div>
                </div>
                <!-- Carousel nav -->
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                </div>
            </div>

            <!-- Example row of columns -->
            <div class="row">
                <div class="span4">
                    <h2><img src="/assets/community.svg" style="width:32px; height:32px;"/>  Who we are.</h2>
                    <p style="font-size: 15px;">Passionate advocates of natural healthcare and general wellness </br></br>
                        Independent consumers of healthcare information that want to make better healthcare decisions</br></br>
                        Internet users that want to cut through the noise to find what's relevant to us, what works and what doesn't. <b><a href="#whoWeAre" data-toggle="modal">Read More</a></b> about us!</p>
                    <!-- Modals -->
                        <div id="whoWeAre" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel">Who We Are.</h3>
                            </div>
                            <div class="modal-body">
                                <p style="font-size: 15px;">
                                    Here at wellbe we believe there are non-chemical, noninvasive solutions to many health issues today that can provide more than just an indefinite bandaid.  The trouble is, there is a lot of noise out there. There is plenty of bad information and the good information is often buried in random places most consumers cannot or don't know how to find. The internet has allowed us to not just take a doctor's word as fact, we can now research and understand all of our options and make better decisions. 
                                </br>
                                </br>
                                    We think wellbe can change the healthcare system in some small way by aggregating natural, complementary and alternative healthcare information as well as general wellness, nutritional and lifestyle tips from a variety of notable sources and by providing a community platform for people dedicated to living a more natural life. By sharing your health stories and your health questions, the wellbe network can help answer your questions and solve your health challenges. From medical databases to NYTimes Health articles, we'll comb through the noise and provide you with as comprehensive a view as we can of all your options. Sign up today and join the wellbe movement.</p>
                            </div>
                            <div class="modal-footer">
                                <button class="btn" data-dismiss="modal" aria-hidden="true">Go Back</button>    
                            </div>
                        </div>
                </div>
                <div class="span4">
                    <h2><img src="/assets/hospital.svg" style="width:35px; height:32px;"/>What you get.</h2>
                     <p style="font-size: 15px;">
                            Individualized curation of medical studies, health publications, and user experiences pertinent to your condition and/or therapy.</br></br>
                            Ability to share your success stories to help others (anonymously if desired)</br></br>
                            Access to other users' success stories to help you.
                    </p>
                </div>
                <div class="span4">
                    <h2><img src="/assets/gears2.svg" style="width:32px; height:32px;"/>  How it works.</h2>
                    <p style="font-size: 15px;">
                        <ol>
                            <li>Submit your information request</li></br>
                            <li>Pay a fee based on how quickly you want your information delivered</li></br>
                            <li><em><b>SPECIAL:</b> as a beta-user, complete a number of small tasks to <b style="font-size:16px;">reduce your cost to $0!</b></em></li>
                        </ol>
                    </p>
                </div>
            </div> 
              <hr>
        <div class="row">
            <%= render "/users/form" %>
        </div>
        </div><!-- /container -->

        
        <div class="span12">  
            <hr style="bottom-margin:10px;">
        <footer>
        <div class="row">
            <div class="span6">
                <p> View our <%= link_to 'Terms and Conditions', :controller => "home", :action => "terms" %> and <%= link_to 'Privacy Policy', :controller => "home", :action => "privacy" %></p>
            </div>
            <div class="span6">
            <p>&copy; Wellbe 2013</p>
        </div>
        </div>
        </footer>
        </div>
    </body>
</html>

app/views/home/privacy.html.erb
<body>
<p style="text-align:center;"><%= link_to 'Click here', :controller => "home", :action => "index" %> to go back.</p>
<h1>Wellbe Privacy Policy</h1> 

Wellbe understands how important the privacy of personal information is to our users.   We understand that your privacy matters and we respect your privacy choices. 
Information Collected About You 
We may collect “Personal Information” about you – such as your name, address, telephone number, email address or health information – in the following ways:
When you register for or update an existing profile on our web sites
When you sign-up for newsletters or other communications from Wellbe;
When you participate in an online survey; or
When you provide personal information in a community area or other public forum.
What Choices Do I Have? 
If you do not want your Personal Information used by Wellbe as provided in this Privacy Policy, you should not register as a member or for any specific tool or application that collects Personal Information. You may correct, update or review Personal Information you have submitted through registration. If you have registered and no longer want Wellbe to use your Personal Information, you should delete your information as described in this Policy.
How Information Collected About You Is Used 
We may use information we collect about you to: 
Administer your account;
Provide you with access to particular tools and services;
Respond to your inquiries and send you administrative communications; 
Obtain your feedback on our sites and our offerings;
Statistically analyze user behavior and activity;
Provide you with more relevant content and advertisements; 
Conduct research and measurement activities; or
Send you personalized emails or secure electronic messages pertaining to your health interests, including news, announcements, reminders and opportunities.
We may combine Personal and Non-Personal Information collected by Wellbe about you, and may combine this information with information from external sources.  Third parties may also use Non-Personal Information in order to display advertising that reflects the interests and preferences of our user community. 
With Whom Do We Share Your Information? 
Wellbe will not disclose any Personal Information about you unless specifically agreed to you by you or:
To comply with legal requirements, such as a law, regulation, search warrant, subpoena, or court order;
In special cases, such as in response to a physical threat to you or others. 
Wellbe does not make your Personal Information available to third parties for their marketing purposes.
How Do We Secure and Retain Your Information? 
We have put in place technical, physical, and administrative safeguards to protect the Personal Information that we collect. 
Contact Wellbe 
Please send us an email using the Contact Us link at the bottom of every page of our site if you have any questions about this Privacy Policy or the Personal Information we maintain about you. 



</body>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Wellbe", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wellbe" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wellbe" %>">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <!--<script src="/assets/stripe.js"></script> -->
    <script src="/assets/bootstrap-dropdown.js"></script>
    <script src="https://checkout.stripe.com/v2/checkout.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js"></script>

    <!-- TOOK OUT THE TAG THING HERE -->
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/"><img src="/assets/wellbe_logo2.png" style="width:82px; height:30px;"/></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li style="font-size: 18px;"><a href="/sessions/new" style="padding-top:20px; padding-bottom:0px;">Login</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top:21px; padding-bottom:0px; font-size: 17px;">Our Sources<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li class="nav-header">Integrative Medicine</li>
                                    <li><a href="http://www.nccam.nih.gov" target="_blank">NIH</a></li>
                                    <li><a href="http://www.naturalmedicine.com" target="_blank">NaturalMedicine.com</a></li>
                                    <li><a href="http://www.sciencebasedmedicine.org" target="_blank">ScienceBasedMedicine.org</a></li>
                                    <li><a href="http://www.imjournal.com" target="_blank">IMJournal.com</a></li>
                                    <li class="nav-header">Nutrition and Well-Being</li>
                                    <li><a href="http://www.yogasite.com" target="_blank">Yoga</a></li>
                                    <li><a href="http://www.naturopathic.org" target="_blank">Naturopathy</a></li>
                                    <li class="nav-header" style="size: 20px">...and many more!</li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main" role="main">
      <div class="container">
           <div class="row">
              <%= render 'layouts/messages' %>
                <%= yield %>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/no_pay/nopayNotification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
   <h2>Someone signed up for wellbe from the NOPAY version of the site.</h2>
   <h4>go to getwellbe.herokuapp.com/users to see who it is</h4>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<table>
  <tr>
    <!-- <th>Customer Id</th> -->
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profile.each do |profile| %>
  <tr>
    <td><%= profile.email %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/profiles/new.html.erb
<h1>You're almost there!</h1>

<h3>Confirm your email, and give us a password, and you'll have your content!</h3>

<%= form_for @profile do |f| %>
  <% if @profile.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @profile.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/user_signup/notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    Someone just signed up for wellbe! 

  </body>
</html>

app/views/user_signup/notification.text.erb
Someone just signed up for wellbe!

Check out wellbe.herokuapp.com/users to see the new users!

app/views/user_signup/notification_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    Someone just signed up for wellbe! 
    Go to wellbe.herokuapp.com/users to see what their information is.

  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for User.new do |f| %>
  <%= f.error_notification %>
  <div class="span4">
    <%= f.input :email, placeholder: "user@domain.com"%>
</div>
<div class="span4">   
 	<%= f.input :condition, label: "Research Area", placeholder: "Tell us what to research", hint: 'EG: Back Pain and Acupuncture' %>
 </div>
 <div class="span4" style="padding: 23px 0 0 0;">
	<%= f.button :submit, 'Begin curation' %>
 </div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <!-- <th>Customer Id</th> -->
    <th>Email</th>
    <th>Condition</th>
    <th>Sign-up Date </th>
    <th>How Long For Curation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
   <!-- <td><%= user.name %></td> -->
    <td><%= user.email %></td>
    <td><strong><%= user.condition %></strong></td>
    <td><%= user.created_at.localtime %></td>
    <td><strong><%= user.curation %></strong></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>Please enter your information below!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class ="container">
<div class="row" style="margin: 0px auto;"><h1 style="margin: 10px 0px 20px 0px;"><span style="font-size:40px;">Congrats!</span> Just one more thing before you go...</h1></div>

<div class="span12" style=":0px auto;">
  <div class="row" style="margin: 0px auto;">
    <div class="well" style="padding: 5px 19px 5px 19px;">
  <h3 style="text-align: center;">We here at Wellbe want to make sure you are getting the </br>best information possible...but good information takes time to collect!</br></br>Tell us how fast you'd like your information collected, and we'll do the rest!</h3>
<!-- <h4>Here's how to get started:</h4></br>
    <ul style="font-size:17px;">
      <p><i class="icon-user">  Fill out your Wellbe profile</i> </p>
      <p><i class="icon-pencil">  Share your CAM story (anonymously)</i>  </p>
      <p><i class="icon-thumbs-up">  Rate the articles we curate for you</i>  </p>
      <p><i class="icon-edit">  Fill out a quick survey about the website</i></p>
      <p><i class="icon-share">  Refer a friend to Wellbe</i></p>
    </br>
    </ul>
<h4 style="text-align:right;">...do this, and your curated content will be free!</h4> -->
    </div>
  </div>
</div>
<div class="span12" style="margin: 0px auto; text-align: center;">
  <div class="row" style="margin: 0px auto;">

    <h1 style="margin: 0px auto;">Pick a curation method below:</h1>
  </div>
  <div class="row" style="margin: 10px auto;">
          <%= render "/charges/chargeNoStripe" %>
  </div>
      <p style="text-align:center;">If you'd like to go back (and why would you want to?) <%= link_to 'click here', :controller => "home", :action => "index" %>.</p>
  </div>

</div> <!--bigger row div -->

</div><!-- container div -->